<?php

require_once dirname(__FILE__) . '/../Dictionary.php';

/**
 * Test class for Dictionary.
 * Generated by PHPUnit on 2012-01-25 at 16:37:58.
 */
class DictionaryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Dictionary
     */
    protected $object;
    protected $hashLength = 1;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Dictionary('../dictionary.txt', $this->hashLength);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
/*    
    public function testHash(){
        $this->assertEquals('acbd', $this->object->createHash('foo'));
    }
*/    
    public function testDictionary() {
        $this->assertTrue($this->object->checkDictionary('werden'));
    }
/*
    public function testDictionaryNegative() {
        $this->assertFalse($this->object->checkDictionary('frankenstein'));
    }
*/
    public function testDictionaryComplete() {
        $this->assertEquals(0, $this->object->checkDictionaryComplete());
    }
}

?>
